# Site settings
title: Cristhian pin
description: 
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Cristhian pin
user_description: Soy estudiante de la carrera de Software, siempre buscando por nuevos conocimientos en la materia. Me gustaria aprender nuevo programas en el transcurso de la carrera. y pues ahre
email: Cristhianpin92@gmail.com
Estudios-Realizados:
user_Estudios-Realizados:Mi vida como estudiante comenzo en el jardin -Pedacitos de Pintores, siguiendo a la escuela -America Unida, y el colegio -Cayetano Tarruell, y actualmente cruzando en la Universidad de Guayaquil
Acerca-de-Mi:
user_Acerca-de-mi: Mi nombre completo es Cristhian Joel Pin Reyes naci el 29 de Abril de 2002, soy una persona que le gusta aprender a cada momento tengo como hobby rapear, jugar, leer, y ber bideos. Me considero alguien que siempre busca la perfección es ñas cpsas que hace, detesto perder.
#twitter_username: https://twitter.com/b0933f7febd24d2?s=09
#github_username:  cristhianpin
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
