# Site settings
title: Cristhian Pin
description: 
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Cristhian Pin
user_description: Soy estudiante de la carrera de Software, siempre buscando por nuevos conocimientos en la materia. Me gustaria aprender nuevo programas en el transcurso de la carrera.
 Mi vida como estudiante comenzo en el jardin -Pedacitos de Pintores, siguiendo a la escuela -America Unida, y el colegio -Cayetano Tarruell, y actualmente cruzando en la Universidad de Guayaquil
 Mi nombre completo es Cristhian Joel Pin Reyes naci el 29 de Abril de 2002, soy una persona que le gusta aprender a cada momento tengo como hobby rapear, jugar, leer, y ver videos. Me considero alguien que siempre busca la perfección es las cosas que hace, detesto perder.
 
 -Tema de interes-
 1.Mi punto de vista en la carrera. Es a un corto plazo tener una propia empresa de desarrollo y evolución del software y dejar a Ecuador en un punto alto en la industria.
 2.Musica. Desde niño me a gustado los diversos estilos musicales que existen actualmente soy un competidor en batallas de rap no lo considero mi genero favorito, pero el batallar me ayuda a desestresarme.
 3.Mi gusto a la informatica. La computación y la tecnoliga siempre me a llamado la atención porque la mecatronica fue una de mis primeras opciones a estudiar, pero luego me di cuenta que mucho circuito me estresaba, igual he trabajado con un poco de robotica llegando a hacer carros a control remoto, ascensor, sensor con leds, entre otras cosas
 
email: Cristhianpin92@gmail.com
#twitter_username: https://twitter.com/b0933f7febd24d2?s=09
#github_username:  cristhianpin
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
