# Site settings
title: Cristhian pin
description: 
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Cristhian pin
user_description: Soy estudiante de la carrera de Software, siempre buscando por nuevos conocimientos en la materia. Me gustaria aprender nuevo programas en el transcurso de la carrera.
user_title: Estudiante de Software
email: Cristhianpin92@gmail.com
#twitter_username: "crispin"
#github_username:  cristhianpin
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
